# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d109fa55de54a49f9b60a23df050c07f20bf0470706b6d9a5c9dfe6d9efac76383c5a63afaf7193766b458538b30a4d03ecdbe71bf5ad2bf1ba39d6b39953218

test:
  secret_key_base: 5818cea8dba4e9525e0ad4a0817c1514e513b2e1e89e20da701ee8c2210802c1a2838209128c1551fb422b9f20a559221b6a0ffbc2fb7611beb8161e04af570f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
